### ISSUE TITLE
GMV (Gross Merchandise Value)

### ISSUE THREAD

**Issue by BOC111** [tiki/purchase#1]
### Requirement
We have had a request for a GMV calculation for the retail dataset. 

**Definition**
Gross Merchandise Value (GMV) is a metric that measures your total value of sales over a certain period of time. It’s a metric most commonly used in the eCommerce industry and is sometimes referred to as Gross Merchandise Volume. 

### Formula
The formula is very simple 
**Gross Merchandise Value =  Sales Price of Goods x Number of Goods Sold**
So let’s say you sell 10 products for $100 each, your Gross Merchandise Value would amount to $1,000.

It would probably make sense for us to offer this for the top 20 retailers as an option.

**Comment by BOC111** [comment]
Can you 

- take "merchant_name" and sum "amount" for each retailer. This will give is a 2 column table of retailers and a $ amount for each one. 
- Total up all the retailers for that month. This will give us a single $ number.

**Comment by mike-audi** [comment]
delivered to @BOC111 via discord.
