### ISSUE TITLE
Dataset Description

### ISSUE THREAD

**Issue by BOC111** [tiki/purchase#17]
### Reason

A short description of the dataset.

### Description

A text summary description of the dataset. 

The description will be 2/3 sentences giving a potential buyer an overview of the set.

### Success Criteria

- [ ] A description of each dataset

### Additional Information

**Architecture**

- what third-party tooling/APIs are needed - None
- which tiki systems are involved

**Value Prop**

- value to tiki - _It provides metadata to the dataset for searching and categorising_
- value to purchaser - _A summary that will enable them to decide if it matches their needs or not_
- value to vendor companies - _It provides them with an opportunity to describe their data_

**Specs**

- required features - _1. A freeform text input when the dataset is loaded onto the Tiki platform. 2. The ability to display the text in a "catalogue type" listing._
- why "these" features - _We have to record and display it._
- purchaser details - _When the dataset is listed for the first time the vendor/publisher will describe the dataset in several sentences to improve their chances of selling the data. The better the description the better the chance of a purchaser engaging._

**UX**

- wireframe - see below

**Comment by BOC111** [comment]
Requirements - a text box to be editable by Tiki staff.

**Comment by BOC111** [comment]
By clicking the "get started" button, the following actions will commence-

1. A new account will be created with the details written to the CRM/Account platform
2. A validation email will be sent to the submitted email address.
3. When the email is validated, a second email will be sent with details of haw to connect to the chosen cloud provider.

**Comment by mike-audi** [comment]
I don't understand what this is. The first dataset and docs are here: https://github.com/tiki/purchase/blob/main/README.md

This story should be to write the description for that dataset.
