### ISSUE TITLE
Data Purchasing APIs (first iteration)

### ISSUE THREAD

**Issue by timoguin** [tiki/purchase#43]
# Description

Design and develop the APIs required for users to be able to estimate costs and create subscriptions to our datasets.

## API Functionality

- Work with datasets (list and describe available datasets)
- Work with connections (list, describe, and create connections for data access)
- Work with subscription estimates (validate queries, return cost estimates and stats for a subscription query)
- Work with subscriptions (list, describe, create, pause, and delete subscriptions)
- Work with delivery channels (list, describe, and create delivery channels for external data delivery)

# Issues

- [x] #47
- [x] #48
- [x] #49
- [x] https://github.com/tiki/core-account-service/issues/274
- [x] https://github.com/tiki/core-account-service/issues/275
- [x] https://github.com/tiki/core-account-service/issues/276
- [ ] https://github.com/tiki/core-account-service/issues/277
- [x] https://github.com/tiki/core-account-service/issues/278
- [x] https://github.com/tiki/core-subscription/issues/1
- [x] https://github.com/tiki/core-subscription/issues/2
- [x] https://github.com/tiki/core-subscription/issues/3

## Later Iterations

- Delivery Channel APIs

**Comment by mike-audi** [comment]
Notes to self on known issues for next rev(s) - new stories are required

- Update queries are not (yet) implemented
- Create query results are stuck in "pending" even though they work (fix the hacky always fetch)
- Cleanrooms do not auto create DBs and set permissions (yet)
- Pause/Stop is not implemented
- Need to add billing information (do we add to estimate results?)
- Query results need revision (what are even the results for CTAS and Merge)
- Need an endpoint to list all cleanrooms
- The API docs and naming need love
- Need a lambda to expose tables and columns
- very future - need an alternative to iam policy for glue catalog 
- sanitize/alert against invalid table names

**Comment by mike-audi** [comment]
@mike-audi create stories.
