### ISSUE TITLE
Subscription Estimator APIs

### ISSUE THREAD

**Issue by timoguin** [tiki/purchase#47]
The _Subscription Estimator_ APIs should accept a SQL query and return a monthly cost estimate, some basic stats about the dataset, and a small sample of the data.

# Features

- Validate the provided SQL query
- Create a background job for running a wrapped version of the provided query. At a basic level, we can wrap queries in a `SELECT count(*) FROM`
- Retrieve monthly cost estimate for a subscription
- Retrieve stats about the generated dataset (no. of records, users, publishers, size, etc)
- Retrieve a small sample of the generated dataset

# Actions / Endpoints

- `CreateSubscriptionEstimate`: take a SQL query, validate it, kick off a background job to run it, and return an estimate ID
- `GetSubscriptionEstimateCost`: take an estimate ID and return the estimated monthly costs
- `GetSubscriptionEstimateStats`: take an estimate ID and return stats about the dataset
- `GetSubscriptionEstimateSample`: take an estimate ID and return a small sample of the data

These endpoints can be combined and/or broken up as needed. I'm not 100% set on them.

**Comment by mike-audi** [comment]
closed in favor of https://github.com/tiki/core-account-service/issues/274
