### ISSUE TITLE
Subscription Management APIs

### ISSUE THREAD

**Issue by timoguin** [tiki/purchase#48]
The _Subscription Management_ APIs allow users to create and manage dataset subscriptions. This is the primary interface for selling data.

# Features

Basic CRUD operations for managing dataset subscriptions. Users should be able to supply a SQL query to use as the basis for a subscription.

They should also be able to update / modify the subscription, pause it, and delete it.

Users should not be required to create a subscription estimate, but, if a user _has_ already created an estimate, allow them to provide an estimate ID to the subscription creation endpoint. This way they can utilize the query they have already created. The web UI can handle this automatically when a user is using the subscription builder.

# Actions / Endpoints

- `CreateSubscription`: validate a provided SQL query and create a subscription
- `ListSubscriptions`: list a user's configured subscriptions
- `GetSubscription`: take a subscription ID and return details about a subscription
- `PauseSubscription`: take a subscription ID and pause any workflows that update the data (maybe a later iteration?)
- `DeleteSubscription`: take a subscription ID and delete the subscription and any background tasks

The `Create`, `Pause`, and `Delete` endpoints will need to kick off background workflows to manage things like scheduled queries that generate data cleanrooms.

**Comment by mike-audi** [comment]
closed in favor of https://github.com/tiki/core-account-service/issues/275
